<?php 
// Debugged using ELM (GPT 5.2), https://elm.edina.ac.uk/elm-new
// Example set page
// Providing information about the example data set results and interpretation

session_start();
require_once 'set_cookies.php';
require_once 'login.php';
session_write_close();

// Database connection, adapted from class code
try {
	$dsn = "mysql:host=127.0.0.1;dbname=$database;charset=utf8mb4";
	$conn = new PDO($dsn, $username, $password);
	$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (Throwable $e) {
	http_response_code(500);
	die("Database connection failed");
}

// Retrieve information for latest example job
// TODO: add an occasional run to update example set
try {
	$stmt = $conn->prepare("
	SELECT jobs.job_id, jobs.status, jobs.error_message, jobs.query_id, jobs.job_params,
	queries.protein_family, queries.taxon
	FROM jobs
	JOIN queries ON queries.query_id = jobs.query_id
	WHERE jobs.is_example = 1
	AND queries.protein_family = ?
	AND queries.taxon = ?
	ORDER BY jobs.job_date DESC, jobs.job_id DESC
	LIMIT 1
	");
	$stmt->execute(['glucose-6-phosphatase', 'aves']);
	$job = $stmt->fetch(PDO::FETCH_ASSOC);

	// Checking if exists
	// (Really bad if doesn't...)
	if (!$job) {
		http_response_code(404);
		require __DIR__ . '/not_found.php';
		die();
	}

	$jid = (int)$job['job_id'];

} catch (Throwable $e) {
	http_response_code(500);
	die("Could not retrieve example dataset");
}

echo <<<_HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="/~s2883992/website/styles.css">
<title>Example Dataset</title>
</head>
<body>
_HTML;

include 'cookies.html';
include 'menuf.php';

// Sticky left menu, informed by ELM (GPT 5.2), https://elm.edina.ac.uk/elm-new
echo <<<_NAV
<div class="page-shell">
<aside class="page-side-nav">
<h2>On this Page</h2>
<ul>
<li><a href="#process">Process Outline</a></li>
<li><a href="#outline">Results Outline</a></li>
<li><a href="#query_param">Query Parameters</a></li>
<li><a href="#plotcon_res">Plotcon Results</a></li>
<li><a href="#summary">Summary Statistics</a></li>
<li><a href="#files">Downloads</a></li>
<li><a href="#alignment_ajax">Alignment Overview</a></li>
<li><a href="#motif_ajax">Motif Overview</a></li>
<li><a href="/~s2883992/website/query">Run Your Own Query</a></li>
<li><a href="#">Back to Top</a></li>
</ul>
</aside>
<main class="page-main">
<header class="page-title">
<h1>Example Dataset</h1>
<p>
This page presents a precomputed example analysis of 
<b>glucose‑6‑phosphatase</b> proteins from <i>Aves</i> (birds). 
</p>
</header>
<hr>
_NAV;

echo <<<_HTML2
<section id="process">
<h2>Process Outline</h2>
<ol>
<li>Sequence retrieval from the <a href="https://www.ncbi.nlm.nih.gov/protein" target="_blank">NCBI protein database</a> </li>
<li>Multiple sequence alignment using <a href="https://www.ebi.ac.uk/jdispatcher/msa/clustalo" target="_blank">Clustal Omega</a></li>
<li>Generation of a conservation plot using <a href="https://www.bioinformatics.nl/cgi-bin/emboss/plotcon" target="_blank">plotcon</a></li>
<li>Motif detection using 
<a href="https://prosite.expasy.org/" target="_blank">PROSITE</a> patterns via EMBOSS 
<a href="https://www.bioinformatics.nl/cgi-bin/emboss/patmatmotifs" target="_blank">patmatmotifs</a></li>
</ol>
</section><hr>

<section id="outline">
<h2>Results Outline</h2>
<p>This example illustrates the type of output generated by the website.
You can explore the conservation plot, browse the alignment and motif tables, and download all associated files.</p>
<p>The results include:</p>
<ul>
<li><b>Conservation plot</b> (plotcon), showing similarity scores along the alignment.</li>
<li><b>Summary statistics</b> such as sequence count, number of represented organisms, alignment length, and most common motif.</li>
<li><b>Downloadable text files</b> including the MSA and motif hits summary.</li>
<li><b>Interactive alignment and motif tables</b> with filtering and download options.</li>
</ul>
</section> <hr>
_HTML2;

// Rendering the example results page
require_once 'results_content.php';
render_results_content($conn, $job, $jid);
echo <<<_HTML3
</main>
</div>
</body>
</html>
_HTML3
?>

