<?php
session_start();
require_once 'set_cookies.php';
require_once 'login.php';

echo<<<_HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Example dataset</title>
</head>
<body>
_HTML;

include 'menuf.php';
$debug = true;

// Adapted from ELM (GPT 5.2) generated code, https://elm.edina.ac.uk/elm/elm
// Script directories
$base_dir = __DIR__;
$download_py = $base_dir . '/py_scripts/download_sequences.py';
$msa_py  = $base_dir . '/py_scripts/msa_to_sql.py';

// Example parameters
$protein_family = "glucose-6-phosphatase";
$taxon = "aves";
//$user_id = "eg";
$user_hash = $_SESSION['user_hash'];
$is_example = 1;

// Output directories - generated by ELM (GPT 5.2), https://elm.edina.ac.uk/elm-new
$workdir = sys_get_temp_dir() . "/bioapp_" . session_id() . "_" . bin2hex(random_bytes(4)); // Creating a unique temporary working directory per session
if (!mkdir($workdir, 0700, true)) {
    $err = error_get_last();
    die("<pre>Failed to create workdir: " . htmlspecialchars(print_r($err, true)) . "</pre></body></html>");
}
$seq_tsv = $workdir . "/example_record.tsv";
$seq_fa  = $workdir . "/example_record.fasta";

// MySQL connection, adapted from class code
try {
        $dsn = "mysql:host=127.0.0.1;dbname=$database;charset=utf8mb4";
        $conn = new PDO($dsn, $username, $password, array(PDO::MYSQL_ATTR_LOCAL_INFILE => true));
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch(PDOException $e) {
        echo "<br/><br/><b><font color=\"red\">Connection failed</font></b>:<br/>" . $e->getMessage();
}

// Defining a function for system call, returning exit code
function run_cmd($cmd, &$outLines) {
    exec($cmd . " 2>&1", $outLines, $rc);
    return $rc;
}

// Running python script for sequence download
$download_cmd = 'python3 ' . escapeshellarg($download_py) 
	. ' --protein ' . escapeshellarg($protein_family) 
	. ' --taxon ' . escapeshellarg($taxon) 
	. ' --outdir '  . escapeshellarg($workdir);
$download_out=[];
$download_rc = run_cmd($download_cmd, $download_out);

// Checking output for debugging - adapted from ELM (GPT 5.2) code, https://elm.edina.ac.uk/elm-new
if ($debug) {
    echo "<pre>DOWNLOAD CMD:\n" . htmlspecialchars($download_cmd) . "\nRC=$download_rc\nOUT:\n"
      . htmlspecialchars(implode("\n", $download_out)) . "</pre>";
}

// Stopping if exit code is not zero
if ($download_rc !== 0) {
	die("<p style='color:red'>Download failed.</p></body></html>");
}
// Or if files don't exist
if (!file_exists($seq_tsv) || !file_exists($seq_fa)) {
    die("<p style='color:red'>Download finished but TSV/FASTA missing in workdir.</p></body></html>");
}

// Parsing result print from py script - searching for a numeric line
$match_num = 0;
foreach ($download_out as $line) {
    $line = trim($line);
    if ($line !== '' && is_numeric($line)) { 
	    $match_num = (int)$line; 
	    break;
    }
}

//
if ($match_num === 0) {
	die("<p>No sequences found.</p></body></html>");
}
echo "<p>Matches found: " . htmlspecialchars((string)$match_num) . "</p>";
if ($match_num > 1000) {
	echo "<br>Continuing with first 1000 sequences.";
}

// Inserting into MySQL database, debugged using ELM (GPT 5.2), https://elm.edina.ac.uk/elm-new
try {
	// Only inserting entire jobs
	$conn->beginTransaction();

	// Preparing statement for queries insertion
	$queries_insert = "
		INSERT INTO queries (protein_family, taxon)
		VALUES (:pf, :tx)
		ON DUPLICATE KEY UPDATE query_date = CURRENT_TIMESTAMP
	";
	$stmt = $conn->prepare($queries_insert);
	$stmt->execute([':pf' => $protein_family, ':tx' => $taxon]);

	// Retrieving query ID for seq_group
	$q = $conn->prepare("SELECT query_id FROM queries WHERE protein_family = ? AND taxon = ?");
	$q->execute([$protein_family, $taxon]);
	$qid = $q->fetchColumn();

	// Throwing an error if failed to retrieve query ID + debugging
	if (!$qid) {
		throw new RuntimeException("Could not retrieve query_id after insert.");
    	}
	if ($debug) {
		echo "<pre>Query ID: " . htmlspecialchars((string)$qid) . "</pre>";
	}

	// Temporary table to allow upserting, adapted from: https://stackoverflow.com/questions/15271202/mysql-load-data-infile-with-on-duplicate-key-update
	$conn->exec("
        CREATE TEMPORARY TABLE seq_temp (
        accession VARCHAR(255) NOT NULL,
        organism VARCHAR(255) NOT NULL,
        sequence LONGTEXT NOT NULL
        )
	");

	// Loading sequences into temp
	$conn->exec("
	LOAD DATA LOCAL INFILE " . $conn->quote($seq_tsv) . "
        INTO TABLE seq_temp
        FIELDS TERMINATED BY '\t'
        LINES TERMINATED BY '\n'
        (accession, organism, sequence)
	");

	// Upserting into sequences
	$conn->exec("
	INSERT INTO sequences (accession, organism, sequence)
   	SELECT accession, organism, sequence FROM seq_temp
   	ON DUPLICATE KEY UPDATE
   	organism = VALUES(organism),
   	sequence = VALUES(sequence)
   	");

	// Mapping to seq_group, ignoring duplicates
    	$conn->exec("
        INSERT IGNORE INTO seq_group (query_id, accession)
        SELECT " . (int)$qid . ", accession FROM seq_temp
    	");

	// Creating job
    	$stmt = $conn->prepare("
        INSERT INTO jobs (user_hash, query_id, is_example, status)
        VALUES (?, ?, ?, 'pending')
    	");
    	$stmt->execute([$user_hash, $qid, $is_example]);
    	$jid = (int)$conn->lastInsertId();

	// Dropping temporary table
	$conn->exec("DROP TEMPORARY TABLE seq_temp;");

	// Comitting all changes together
    	$conn->commit();


} catch (Throwable $e) {
	// Closing connection
	if ($conn->inTransaction()) {
		$conn->rollBack();
	};
	// Terminating if cannot load data
    	die("<pre>DB load failed:\n" . htmlspecialchars($e->getMessage()) . "</pre></body></html>");
}

// Performing alignment
// Output directories
$msa_outfile_base = $workdir . "/aligned_job_" . $jid;
$msa_fasta = $msa_outfile_base . ".fasta";
$msa_tsv = $msa_outfile_base . ".tsv";
$msa_cmd = "python3 " . escapeshellarg($msa_py) . " "
         . escapeshellarg($seq_fa) . " fasta "
         . escapeshellarg($msa_outfile_base) . " "
         . escapeshellarg($msa_tsv);

// Python script
$msa_out = [];
$msa_rc = run_cmd($msa_cmd, $msa_out);

if ($debug) {
    echo "<pre>MSA CMD:\n" . htmlspecialchars($msa_cmd) . "\n\nRC=$msa_rc\n\nOUT:\n" .
         htmlspecialchars(trim(implode("\n", $msa_out))) . "</pre>";
}

// Checking exit code and files existence, recording error in database
if ($msa_rc !== 0 || !file_exists($msa_tsv) || !file_exists($msa_fasta)) {
    $stmt = $conn->prepare("UPDATE jobs SET status='error', error_message=? WHERE job_id=?");
    $stmt->execute(["MSA failed: " . implode("\n", $msa_out), $jid]);
    die("<p style='color:red'>MSA failed. Job marked as error.</p></body></html>");
}

// Loading alignments and storing MSA file in analysis_outputs
try {
    // Load aligned sequences from tsv
    $conn->exec("
        LOAD DATA LOCAL INFILE " . $conn->quote($msa_tsv) . "
        INTO TABLE aligned_sequences
        FIELDS TERMINATED BY '\t'
        LINES TERMINATED BY '\n'
        (accession, aligned_sequence)
        SET job_id = " . (int)$jid . "
	");

    // Store aligned FASTA text as an output
    // TODO: maybe better to put in a _SESSION global and output all if the user desires in current session
    $msa_text = file_get_contents($msa_fasta);

    $stmt = $conn->prepare("
        INSERT INTO analysis_outputs (job_id, analysis_type, created_at, mime_type, file_name, parameters, text_data)
        VALUES (?, 'msa', NOW(), 'text/plain', ?, ?, ?)
    ");
    $stmt->execute([
        $jid,
        "aligned_job_" . $jid . ".fasta",
        json_encode(['tool' => 'clustalo', 'outfmt' => 'fasta']),
        $msa_text
    ]);


} catch (Throwable $e) {
    // Updating failure and stopping	
    $stmt = $conn->prepare("UPDATE jobs SET status='error', error_message=? WHERE job_id=?");
    $stmt->execute([$e->getMessage(), $jid]);
    die("<pre>Failed storing alignment:\n" . htmlspecialchars($e->getMessage()) . "</pre></body></html>");
}

// Running plotcon
// Files
$plot_prefix = $workdir . "/plotcon_job_" . (int)$jid;

// Building command, parameters for future flexible script
$win_size = 4;
$img_fmt = "png";
// TODO: Potential editions:
// -gtitle $title
// -gxtitle $xlab
// -gytitle $ylab
$plot_cmd = "plotcon " .
    "-sequences " . escapeshellarg($msa_fasta) .
    " -winsize " . (int)$win_size .
    " -graph " . $img_fmt .
    " -goutfile " . escapeshellarg($plot_prefix) .
    " -auto";

$plot_out = [];
$plot_rc  = run_cmd($plot_cmd, $plot_out);

if ($debug) {
    echo "<pre>PLOTCON CMD:\n" . htmlspecialchars($plot_cmd) . "\nRC=$plot_rc\nOUT:\n"
       . htmlspecialchars(implode("\n", $plot_out)) . "</pre>";
}

// Stopping if exit code is not zero
if ($plot_rc !== 0) {
	die("<p style='color:red'>Failed to plot</p></body></html>");
}

// Finding png file path
// Intializing a filepath
$plot_path = null;
// Plotcon produces unpredictable filenames, searching for a pattern
$png_files = glob($plot_prefix . "*." . $img_fmt);  
if ($png_files !== false) {
	foreach ($png_files as $a) {
		if ($plot_path === null) {
			$plot_path = $a;
		} else {
			// Keeping the newest file
			if (filemtime($a) > filemtime($plot_path)) {
				$plot_path = $a;
			}
		}
	}
}
// If file doesn't exist
if ($plot_path === null || !is_file($plot_path) || !is_readable($plot_path)) {
    if ($debug) {
        echo "<pre>plotcon PNG not found or not readable.\nSelected plot_path: " .
             htmlspecialchars(var_export($plot_path, true)) . "\n\nWORKDIR LIST:\n" .
             htmlspecialchars(shell_exec("ls -lah " . escapeshellarg($workdir) . " 2>&1")) .
             "</pre>";
    }
    die("<p style='color:red'>plotcon finished but PNG output was not found.</p></body></html>");
}

if ($debug) {
    echo "<pre>Selected plot PNG: " . htmlspecialchars($plot_path) . "</pre>";
}

// Read outputs
$png_bytes = file_get_contents($plot_path);
if ($png_bytes === false || strlen($png_bytes) < 100) {
    die("<p style='color:red'>Failed to read plot PNG bytes.</p></body></html>");
}

// Store in analysis_outputs
try {
	$stmt = $conn->prepare("
		INSERT INTO analysis_outputs
          	(job_id, analysis_type, mime_type, file_name, parameters, blob_data)
        	VALUES (:jid, 'plotcon', :mime, :fname, :params, :blob)
		");
	// Indicating specific data types for the variables
	$stmt->bindValue(':jid', (int)$jid, PDO::PARAM_INT);
	$stmt->bindValue(':mime', 'image/' . $img_fmt, PDO::PARAM_STR);
    	$stmt->bindValue(':fname', basename($plot_path), PDO::PARAM_STR);
    	$stmt->bindValue(':params', json_encode(['winsize' => $win_size]), PDO::PARAM_STR);
    	$stmt->bindValue(':blob', $png_bytes, PDO::PARAM_LOB);
	$stmt->execute();
	
	// Retrieving analysis ID
	$plot_output_id = (int)$conn->lastInsertId();
    	echo "<p>plotcon stored in DB. output_id=" . (int)$plot_output_id . "</p>";

    	// Show image and download link
	$img_script = 'get_output.php?output_id=' . (int)$plot_output_id;
    	echo "<h3>Conservation plot (plotcon)</h3>";
    	echo "<img style='max-width:900px;width:100%;height:auto;border:1px solid #ccc' "
       	. "src='" . $img_script . "' alt='plotcon plot'>";
	echo "<p><a href='" . $img_script . "&download=1'>Download PNG</a></p>";

} catch (Throwable $e) {
	$stmt = $conn->prepare("UPDATE jobs SET status='error', error_message=? WHERE job_id=?");
	$stmt->execute([$e->getMessage(), (int)$jid]);
	die("<pre>Failed to store plotcon output:\n" . htmlspecialchars($e->getMessage()) . "</pre></body></html>");
}

// patmatmotifs run and SQL loading
// Directories
$pat_py = $base_dir . "/py_scripts/patmat_to_sql.py";
$motif_hits_tsv = $workdir . "/motif_hits_job_" . (int)$jid . ".tsv";

// Running python
$pat_out = [];
$pat_cmd = "python3 " . escapeshellarg($pat_py) . " " .
           escapeshellarg($seq_tsv) . " " .
           escapeshellarg($motif_hits_tsv);
$pat_rc  = run_cmd($pat_cmd, $pat_out);

if ($debug) {
    echo "<pre>PATMATMOTIFS CMD:\n" . htmlspecialchars($pat_cmd) .
         "\nRC=$pat_rc\nOUT:\n" . htmlspecialchars(implode("\n", $pat_out)) . "</pre>";
}

// Updating jobs in case of an error
if ($pat_rc !== 0) {
    $stmt = $conn->prepare("UPDATE jobs SET status='error', error_message=? WHERE job_id=?");
    $stmt->execute(["patmatmotifs python step failed:\n" . implode("\n", $pat_out), (int)$jid]);
    die("<p style='color:red'>patmatmotifs failed. Job marked as error.</p></body></html>");
}

// Or no outptut
if (!file_exists($motif_hits_tsv)) {
    $stmt = $conn->prepare("UPDATE jobs SET status='error', error_message=? WHERE job_id=?");
    $stmt->execute(["patmatmotifs finished but motif hits TSV missing: $motif_hits_tsv", (int)$jid]);
    die("<p style='color:red'>motif hits TSV missing.</p></body></html>");
}

// Trying loading motifs into MySQl
try {
	$load_motifs = "
		LOAD DATA LOCAL INFILE " . $conn->quote($motif_hits_tsv) . "
		INTO TABLE motif_hits
            	FIELDS TERMINATED BY '\t'
            	LINES TERMINATED BY '\n'
            	(@acc, @motif, @start, @end, @score, @mseq)
            	SET
                job_id = " . (int)$jid . ",
                accession = @acc,
                motif_name = @motif,
                start_pos = @start,
                end_pos = @end,
                score = NULLIF(@score, ''),
                matched_sequence = NULLIF(@mseq, '')
		";
	$conn->exec($load_motifs);
	if ($debug) {
		$n = $conn->query("SELECT COUNT(*) FROM motif_hits WHERE job_id=" . (int)$jid)->fetchColumn();
		       	echo "<pre>motif_hits rows for job_id " . (int)$jid . ": " . htmlspecialchars((string)$n) . "</pre>";
		}
// Otherwise updating job faiure
} catch (Throwable $e) {
	$stmt = $conn->prepare("UPDATE jobs SET status='error', error_message=? WHERE job_id=?");
	$stmt->execute([$e->getMessage(), (int)$jid]);
	die("<pre>Failed loading motif hits:\n" . htmlspecialchars($e->getMessage()) . "</pre></body></html>");
}

// Updating job status
$stmt = $conn->prepare("UPDATE jobs SET status='complete' WHERE job_id=?");
$stmt->execute([$jid]);
echo "<p><b>Example job complete.</b> job_id=" . (int)$jid . "</p>";

echo <<<_HTML
</body>
</html>
_HTML;
?>
