<?php
session_start();
require_once 'login.php';

echo<<<_HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Example dataset</title>
</head>
<body>
_HTML;

include 'menuf.php';
$debug = true;

// Adapted from ELM (GPT 5.2) generated code, https://elm.edina.ac.uk/elm/elm
// Script directories
$base_dir = __DIR__;
$download_py = $base_dir . '/py_scripts/example_set.py';
$msa_py  = $base_dir . '/py_scripts/msa_to_sql.py';

// Example parameters
$protein_family = "glucose-6-phosphatase";
$taxon = "aves";
$user_id = "example";
$is_example = 1;

// Output directories - generated by ELM (GPT 5.2), https://elm.edina.ac.uk/elm-new
$workdir = sys_get_temp_dir() . "/bioapp_" . session_id() . "_" . bin2hex(random_bytes(4)); // Creating a unique temporary working directory per session
if (!mkdir($workdir, 0700, true)) {
    $err = error_get_last();
    die("<pre>Failed to create workdir: " . htmlspecialchars(print_r($err, true)) . "</pre></body></html>");
}
$seq_tsv = $workdir . "/example_record.tsv";
$seq_fa  = $workdir . "/example_record.fasta";

// MySQL connection, adapted from class code
try {
        $dsn = "mysql:host=127.0.0.1;dbname=$database;charset=utf8mb4";
        $conn = new PDO($dsn, $username, $password, array(PDO::MYSQL_ATTR_LOCAL_INFILE => true));
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch(PDOException $e) {
        echo "<br/><br/><b><font color=\"red\">Connection failed</font></b>:<br/>" . $e->getMessage();
}

// Defining a function for system call, returning exit code
function run_cmd($cmd, &$outLines) {
    exec($cmd . " 2>&1", $outLines, $rc);
    return $rc;
}

// Running python script for sequence download
$download_cmd = 'python3 ' . escapeshellarg($download_py) 
	. ' --protein ' . escapeshellarg($protein_family) 
	. ' --taxon ' . escapeshellarg($taxon) 
	. ' --outdir '  . escapeshellarg($workdir);
$download_out=[];
$download_rc = run_cmd($download_cmd, $download_out);

// Checking output for debugging - adapted from ELM (GPT 5.2) code, https://elm.edina.ac.uk/elm-new
if ($debug) {
    echo "<pre>DOWNLOAD CMD:\n" . htmlspecialchars($download_cmd) . "\nRC=$download_rc\nOUT:\n"
      . htmlspecialchars(implode("\n", $download_out)) . "</pre>";
}

// Stopping if exit code is not zero
if ($download_rc !== 0) die("<p style='color:red'>Download failed.</p></body></html>");
// Or if files don't exist
if (!file_exists($seq_tsv) || !file_exists($seq_fa)) {
    die("<p style='color:red'>Download finished but TSV/FASTA missing in workdir.</p></body></html>");
}

// Parsing result print from py script - searching for a numeric line
$match_num = 0;
foreach ($download_out as $line) {
    $line = trim($line);
    if ($line !== '' && is_numeric($line)) { 
	    $match_num = (int)$line; 
	    break;
    }
}

//
if ($match_num === 0) {
	die("<p>No sequences found.</p></body></html>");
}
echo "<p>Matches found: " . htmlspecialchars((string)$match_num) . "</p>";
if ($match_num > 1000) {
	echo "<br>Continuing with first 1000 sequences.";
}

// Inserting into MySQL database, debugged using ELM (GPT 5.2), https://elm.edina.ac.uk/elm-new
try {
	// Only inserting entire jobs
	$conn->beginTransaction();

	// Preparing statement for queries insertion
	$queries_insert = "
		INSERT INTO queries (protein_family, taxon)
		VALUES (:pf, :tx)
		ON DUPLICATE KEY UPDATE query_date = CURRENT_TIMESTAMP
	";
	$stmt = $conn->prepare($queries_insert);
	$stmt->execute([':pf' => $protein_family, ':tx' => $taxon]);

	// Retrieving query ID for seq_group
	$q = $conn->prepare("SELECT query_id FROM queries WHERE protein_family = ? AND taxon = ?");
	$q->execute([$protein_family, $taxon]);
	$qid = $q->fetchColumn();

	// Throwing an error if failed to retrieve query ID + debugging
	if (!$qid) {
		throw new RuntimeException("Could not retrieve query_id after insert.");
    	}
	if ($debug) {
		echo "<pre>Query ID: " . htmlspecialchars((string)$qid) . "</pre>";
	}

	// Temporary table to allow upserting, adapted from: https://stackoverflow.com/questions/15271202/mysql-load-data-infile-with-on-duplicate-key-update
	$conn->exec("
        CREATE TEMPORARY TABLE seq_temp (
        accession VARCHAR(255) NOT NULL,
        organism VARCHAR(255) NOT NULL,
        sequence LONGTEXT NOT NULL
        )
	");

	// Loading sequences into temp
	$conn->exec("
	LOAD DATA LOCAL INFILE " . $conn->quote($seq_tsv) . "
        INTO TABLE seq_temp
        FIELDS TERMINATED BY '\t'
        LINES TERMINATED BY '\n'
        (accession, organism, sequence)
	");

	// Upserting into sequences
	$conn->exec("
	INSERT INTO sequences (accession, organism, sequence)
   	SELECT accession, organism, sequence FROM seq_temp
   	ON DUPLICATE KEY UPDATE
   	organism = VALUES(organism),
   	sequence = VALUES(sequence)
   	");

	// Mapping to seq_group, ignoring duplicates
    	$conn->exec("
        INSERT IGNORE INTO seq_group (query_id, accession)
        SELECT " . (int)$qid . ", accession FROM seq_temp
    	");

	// Creating job
    	$stmt = $conn->prepare("
        INSERT INTO jobs (user_id, query_id, is_example, status)
        VALUES (?, ?, ?, 'pending')
    	");
    	$stmt->execute([$user_id, $qid, $is_example]);
    	$jid = (int)$conn->lastInsertId();

	// Dropping temporary table
	$conn->exec("DROP TEMPORARY TABLE seq_temp;");

	// Comitting all changes together
    	$conn->commit();


} catch (Throwable $e) {
	// Closing connection
	if ($conn->inTransaction()) {
		$conn->rollBack();
	};
	// Terminating if cannot load data
    	die("<pre>DB load failed:\n" . htmlspecialchars($e->getMessage()) . "</pre></body></html>");
}

// Performing alignment
// Output directories
$msa_outfile_base = $workdir . "/aligned_job_" . $jid;
$msa_fasta = $msa_outfile_base . ".fasta";
$msa_tsv = $msa_outfile_base . ".tsv";
$msa_cmd = "python3 " . escapeshellarg($msa_py) . " "
         . escapeshellarg($seq_fa) . " fasta "
         . escapeshellarg($msa_outfile_base) . " "
         . escapeshellarg($msa_tsv);

// Python script
$msa_out = [];
$msa_rc = run_cmd($msa_cmd, $msa_out);

if ($debug) {
    echo "<pre>MSA CMD:\n" . htmlspecialchars($msa_cmd) . "\n\nRC=$msa_rc\n\nOUT:\n" .
         htmlspecialchars(trim(implode("\n", $msa_out))) . "</pre>";
}

// Checking exit code and files existence, recording error in database
if ($msa_rc !== 0 || !file_exists($msa_tsv) || !file_exists($msa_fasta)) {
    $stmt = $conn->prepare("UPDATE jobs SET status='error', error_message=? WHERE job_id=?");
    $stmt->execute(["MSA failed: " . implode("\n", $msa_out), $jid]);
    die("<p style='color:red'>MSA failed. Job marked as error.</p></body></html>");
}

// Loading alignments and storing MSA file in analysis_outputs
try {
    // Load aligned sequences from tsv
    $conn->exec("
        LOAD DATA LOCAL INFILE " . $conn->quote($msa_tsv) . "
        INTO TABLE aligned_sequences
        FIELDS TERMINATED BY '\t'
        LINES TERMINATED BY '\n'
        (accession, aligned_sequence)
        SET job_id = " . (int)$jid . "
	");

    // Store aligned FASTA text as an output
    // TODO: maybe better to put in a _SESSION global and output all if the user desires in current session
    $msa_text = file_get_contents($msa_fasta);

    $stmt = $conn->prepare("
        INSERT INTO analysis_outputs (job_id, analysis_type, created_at, mime_type, file_name, parameters, text_data)
        VALUES (?, 'msa', NOW(), 'text/plain', ?, ?, ?)
    ");
    $stmt->execute([
        $jid,
        "aligned_job_" . $jid . ".fasta",
        json_encode(['tool' => 'clustalo', 'outfmt' => 'fasta']),
        $msa_text
    ]);

    // Updating job status
    $stmt = $conn->prepare("UPDATE jobs SET status='complete' WHERE job_id=?");
    $stmt->execute([$jid]);

    echo "<p><b>Example job complete.</b> job_id=" . (int)$jid . "</p>";

} catch (Throwable $e) {
    // Updating failure and stopping	
    $stmt = $conn->prepare("UPDATE jobs SET status='error', error_message=? WHERE job_id=?");
    $stmt->execute([$e->getMessage(), $jid]);
    die("<pre>Failed storing alignment:\n" . htmlspecialchars($e->getMessage()) . "</pre></body></html>");
}

    
echo <<<_HTML
</body>
</html>
_HTML;
?>
